### ISSUE TITLE
Deleteing a product causes a 500 error

### ISSUE THREAD

**Issue by RickCarlino** [nerves-hub/nerves_hub_web#698] opened 2020-11-19 15:41 UTC
When deleting a product from Nerves Hub web interface, the server returns a 500 error and does not delete the resource.

**To Reproduce**
1. Login
2. Visit `https://www.nerves-hub.org/org/$ORG_NAME/$PRODUCT_NAME/edit`
3. Click REMOVE PRODUCT
4. Observe "Internal server error" page.

**Screenshots**
![image](https://user-images.githubusercontent.com/1388608/99688383-56aca180-2a4b-11eb-9ccf-07fcbd954b08.png)

**Comment by jjcarstens** [comment] 2020-11-30 15:32
I think there was downtime at this moment or something has already gone into place to fix this. I am unable to reproduce locally or in production so I think I'm going to call this "fixed" for now

**Comment by RickCarlino** [comment] 2020-11-30 15:57
@jjcarstens Perhaps there is some legacy data at play that is specific to our (older) account? I am still able to consistently reproduce on my specific account.

**Comment by jjcarstens** [comment] 2020-11-30 16:02
Can you provide some examples of types of product names you're trying to delete? Have these products been recently created? Or are they old products?

**Comment by jjcarstens** [comment] 2020-11-30 16:03
O, and also - Do your products still have deployments and/or firmwares associated with it? Are there still devices on the product?

**Comment by RickCarlino** [comment] 2020-12-01 14:01
@jjcarstens 

 > Can you provide some examples of types of product names you're trying to delete?

 The product name is `farmbot` and it can be found in the following org(s): `farmbot-legacy-0`, `farmbot-legacy-1`, `farmbot-legacy-2`. In all cases deletion results in a 500 error.

 > Have these products been recently created? Or are they old products?

They are very old. I don't know the exact time frame, but we were one of the first users on the system and it goes back to the pre-alpha days of the codebase. This is why I thought maybe it was related to a legacy data / bad schema issue. That's just a hunch though.

 > Do your products still have deployments and/or firmwares associated with it? Are there still devices on the product?

Previously they did. I deleted all the deployments just now. Removing all associated deployments fixes the 500 error.

 * It seems like this is indeed just a case of needing to delete a deployment prior to deleting an org, though the 500 error was unexpected.
 * It would be nice if deleting a product did a cascading deletion of devices, as we have over 1,000 devices. That is going to be a lot of mouse clicks to delete the org, unless there is an easier way to do it that I am unaware of.
 * While deleting deployments, I hit a 502 error and am no longer able to continue deletions- perhaps my IP hit a rate limit? I can raise a separate issue if necessary. Please let me know.

**Comment by joshk** [comment] 2023-12-06 00:23
Although its not confirmed if this is fixed, I would suggest closing this issue as it's been three years, and we are planning some changes to the UI and core concepts for the 2.0 release.

**Closed** 2023-12-06 02:01 UTC
