### ISSUE TITLE
Product /list does not show All Products

### ISSUE THREAD

**Issue by jjcarstens** [nerves-hub/nerves_hub_web#390] opened 2019-03-25 20:00 UTC
**Describe the bug**
When visiting `/products` list view, it does not list any of the products. However, I can still view an individual product by manually inputting its url.

**To Reproduce**
1. Go to `/products` to view list of all products
2. Notice there are no products in the list

**Expected behavior**
See a list of all the products for that organization

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3
 - Browser: Chrome, Safari
 - Version: 73.0.3683.86. 12.0.3

**Additional context**
This is when using nerves-hub.org directly. I technically haven't tested on `master`

**Comment by jlmcgehee21** [comment] 2019-03-26 16:13
@jjcarstens -- I could not reproduce locally with master with the seeded user.  We also have tests covering this, which are not failing 🤔 

@mobileoverlord -- do you know if any of the product user role stuff could be affecting this?  I'll dig through the source a bit, but I'm not really familiar with the implementation details for that feature.

**Comment by jlmcgehee21** [comment] 2019-03-26 16:17
Maybe a `ProductUser` record didn't get added in the migration, which would cause the query that's being used to populate `/products` to return an empty list?

**Comment by jjcarstens** [comment] 2019-03-26 16:18
If it helps at all, my user was just created yesterday.

I’m still working on getting nerves-hub to run locally to try and reproduce there as well

**Comment by jlmcgehee21** [comment] 2019-03-26 16:22
That does help.  So maybe the product creation isn't making proper associations in the DB after the product user roles got put in place. :eyes:

**Comment by jlmcgehee21** [comment] 2019-03-26 16:54
@jjcarstens -- just to be sure.. You have the proper `org` selected in the leftmost field of the navbar?

**Comment by jlmcgehee21** [comment] 2019-03-26 17:28
I'm a bit perplexed by this.  The create list functions seem to be working properly, as well as the view.  I found a case that wasn't covered by a test, but the new test did not uncover a bug...

**Comment by jjcarstens** [comment] 2019-03-26 19:16
Quick update: Have been trying to help @jlmcgehee21 troubleshoot this. So far I've been able to create a new org, create a new product, and see that in the products list of that new org under the same user.

So this seems to be specific to the existing organization that I was added to not showing its products in the list view. Could also mean that data hasn't been migrated and those products are not correctly associated to the org?

**Comment by jjcarstens** [comment] 2019-04-17 16:20
So I ended up tracking this down. Looks like when we create/add user to an org, we create an `OrgUser` but not a `ProductUser`. And when we try to fetch the products to list, it's [scoped to `ProductUser`](https://github.com/nerves-hub/nerves_hub_web/blob/master/apps/nerves_hub_web_core/lib/nerves_hub_web_core/products.ex#L17) which doesn't exist, which means no products show up.

Creating a new product also creates a new ProductUser which is why it shows after adding a product

**Comment by jjcarstens** [comment] 2019-04-17 16:36
In fact, just to elaborate - A product only gets link to whoever creates it and only they can view/interact with the product. Also, creating a product creates a new `ProductUser` _every_ time wether the user already has a `ProductUser` or not. I'm guessing there is a lot of cleanup to be done to products...

**Comment by jjcarstens** [comment] 2019-04-17 20:55
This will be resolved by https://github.com/nerves-hub/nerves_hub_web/pull/434

**Comment by fhunleth** [comment] 2019-04-18 13:54
@jjcarstens Now that #434 has been merged, does this work for you?

**Comment by jjcarstens** [comment] 2019-04-18 14:44
No. Looks like I was mistaken and the PR changed how we lookup a role for controller actions, but we still need to change the query to return the orgs products. Its still scoped to get only products the user created

**Comment by mobileoverlord** [comment] 2019-04-18 14:55
Oh right, I knew I missed a part of that.

**Closed** 2019-04-18 15:58 UTC
