### ISSUE TITLE
Can't delete firmware and it's not in a deployment

### ISSUE THREAD

**Issue by fhunleth** [nerves-hub/nerves_hub_web#201] opened 2018-08-17 02:20 UTC
Here's the log:
```
fhunleth@halfmarathon:~/smartrent/smartrent_hub_fw (nerves-hub *)$ mix nerves_hub.deployment list
Local user password: 

Deployments:
------------
  name:      frank-dev
  is_active: true
  firmware:  5144fc24-77cd-5689-8f3e-bf3df2cf4e4d
  conditions:
    tags: [dev]
------------

fhunleth@halfmarathon:~/smartrent/smartrent_hub_fw (nerves-hub *)$ mix nerves_hub.firmware list
Local user password: 

Firmwares:
------------
  product:      smartrent_hub_fw
  version:      0.2.1
  platform:     Smartrent Hub
  architecture: arm
  uuid:         5144fc24-77cd-5689-8f3e-bf3df2cf4e4d
------------
  product:      smartrent_hub_fw
  version:      0.2.0
  platform:     Smartrent Hub
  architecture: arm
  uuid:         eb0d54e9-a788-5aab-276e-e222793e4e25

fhunleth@halfmarathon:~/smartrent/smartrent_hub_fw (nerves-hub *)$ mix nerves_hub.firmware delete eb0d54e9-a788-5aab-276e-e222793e4e25

UUID: eb0d54e9-a788-5aab-276e-e222793e4e25
Delete Firmware? [Yn] 
Local user password: 
Failed to delete firmware 
reason: {:error, %{"errors" => %{"detail" => "Internal Server Error"}}}
```

**Comment by fhunleth** [comment] 2018-08-17 02:34
Yep. Once I updated the device that was holding the old firmware hostage, I was able to delete it.

**Comment by jlmcgehee21** [comment] 2018-09-05 02:52
I think this is desired behavior, right @fhunleth?  If so, can we close this issue?

**Comment by fhunleth** [comment] 2018-09-05 05:03
No, this isn't desired behavior. It needs to always be possible to delete firmware images. There are a least a couple reasons to delete a firmware image. The first is to keep the account under the firmware image limit. Another is to remove known bad firmware images. Devices can't be allowed to prevent firmware deletes since they're frequently outside the control of the people running the firmware update  server. For example, if a customer turns a device off, in most cases, I wouldn't be able to call them up to turn their device on so that I could upgrade it to release the lock on a firmware entry.

**Comment by jlmcgehee21** [comment] 2018-09-05 08:05
Ah, right. We had a call about this and failed to document it, iirc.  I'm curious if this is actually still a problem due to the various migrations we've gone through.  Thanks for the update.

**Comment by jjcarstens** [comment] 2019-04-30 18:42
I've confirmed that if a firmware is not tied to a deployment, I can delete from the web UI _and_ from CLI via `mix nerves_hub.firmware delete` so calling this fixed

**Closed by jjcarstens** 2019-04-30 18:42 UTC
